name: Update lists

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 0,12 * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - run: bun src/index.ts
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: 'lists/*.txt'
          commit_message: Generate lists from API